name: piminnovictus
description: "A new Flutter project."

# Si vous souhaitez publier ce projet sur pub.dev, retirez 'none'
publish_to: 'none'

# Version de l'application (par défaut 1.0.0+1)
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  animated_text_kit: ^4.2.2
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.1
  url_launcher_platform_interface: ^2.3.2
  url_launcher_web: ^2.3.3


  fl_chart: ^0.66.0  # Remplace par la dernière version disponible


# Dépendances pour le développement
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo01.png"
  adaptive_icon_background: "#000000"  # Specify a background color
  adaptive_icon_foreground: "assets/logo01.png"
  remove_alpha_ios: true

  flutter_lints: ^4.0.0

# Configuration Flutter (Material Design, polices et assets)
flutter:
  uses-material-design: true

  # Déclarer les fichiers assets ici si nécessaires (images, fonts, etc.)
  assets:
    - assets/
    - assets/user.jpg
    - assets/Dashboard.png
    - assets/back.png

  #   - assets/images/
  #   - assets/fonts/
