name: piminnovictus
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.3  # Garde uniquement cette version
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  animated_text_kit: ^4.2.2
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.1
  url_launcher_platform_interface: ^2.3.2
  url_launcher_web: ^2.3.3
  http : ^1.3.0
  table_calendar: ^3.0.8
  fl_chart: ^0.66.0  # Remplace par la dernière version disponible
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.2
  flutter_secure_storage: ^9.2.2
  geolocator: ^13.0.2
  weather: ^3.1.1
  intl: ^0.19.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  flutter_stripe: ^10.0.0  # Mets la dernière version
  firebase_core: ^2.32.0  # Dernière version compatible


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo01.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo01.png"
  remove_alpha_ios: true
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/user.jpg
    - assets/Dashboard.png
    - assets/back.png

